import type { ModuleAclDefinition, ModuleFeatureDefinition, UserRole } from './modules';

/**
 * Extensão do catálogo vivo: ações granulares por módulo (feature JSONB + ACL com o MESMO nome).
 * `src/config/modules.ts` mescla este mapa em `SYSTEM_MODULES` / `EXTRA_ACL_RESOURCES`, então
 * UserEditor, RolePermissions e `POST /api/acl/init` leem tudo da mesma fonte.
 *
 * Contrato dos defaults (nunca conceder algo novo a USER):
 *  - `A` (ALL) só para ações pessoais que o USER já faz (ver/baixar o próprio, assinar, bater ponto).
 *  - Ação aplicada em rota: default = exatamente quem passava pelo gate de papel antes (`S` = ADMIN/MANAGER,
 *    `O` = só ADMIN). O grant só SOMA usuários além do papel.
 *  - Ação criada e ainda não aplicada: conservador (`S`/`O`); revisar o default ao ligar na rota.
 *  - `N` ([]) = sem default; só quem receber o grant em /admin/users.
 *  - Nunca `A` em módulo cujo catálogo não tem ACL `A` hoje (ACL de USER habilita o módulo no setor estrito).
 */
const A: UserRole[] = ['ADMIN', 'MANAGER', 'USER'];
const S: UserRole[] = ['ADMIN', 'MANAGER'];
const O: UserRole[] = ['ADMIN'];
const N: UserRole[] = [];

/** [sufixo, rótulo PT-BR, nível ACL (0 ver, 1 criar, 2 gerir, 3 admin), defaults]. */
type GrantDef = readonly [suffix: string, label: string, level: number, roles: UserRole[]];

export interface GrantSet {
  features: ModuleFeatureDefinition[];
  acl: ModuleAclDefinition[];
}

function grantSet(prefix: string, defs: readonly GrantDef[]): GrantSet {
  const features: ModuleFeatureDefinition[] = [];
  const acl: ModuleAclDefinition[] = [];
  for (const [suffix, label, level, roles] of defs) {
    const name = `${prefix}.${suffix}`;
    features.push({ key: name, title: label, description: `${label} (${name})`, defaultRoles: roles, userEditor: true });
    acl.push({ name, action: suffix, description: label, level, defaultRoles: roles });
  }
  return { features, acl };
}

/** Chave = `key` do módulo em SYSTEM_MODULES. O prefixo segue o recurso ACL do módulo. */
export const MODULE_GRANTS: Record<string, GrantSet> = {
  dashboard: grantSet('dashboard', [
    ['view', 'Visualizar dashboard', 0, A],
    ['customize', 'Personalizar cards do dashboard', 0, A],
    ['pendencies.view', 'Ver pendências no dashboard', 0, A],
    ['cards.manage', 'Gerenciar cards do dashboard (admin)', 3, O],
  ]),
  noticias: grantSet('news', [
    ['view_drafts', 'Ver rascunhos de notícias', 1, S],
    ['unpublish', 'Despublicar notícias', 2, S],
    ['archive', 'Arquivar notícias', 2, S],
    ['pin', 'Fixar/destacar notícias', 2, S],
    ['categories.manage', 'Gerenciar categorias de notícias', 2, S],
    ['attachments.upload', 'Anexar arquivos em notícias', 1, S],
    ['attachments.download', 'Baixar anexos de notícias', 0, A],
    ['viewers.view', 'Ver quem visualizou a notícia', 3, O],
    ['export', 'Exportar notícias e engajamento', 2, S],
    ['notify', 'Notificar usuários ao publicar', 2, S],
    ['comments.moderate', 'Moderar comentários das notícias', 3, O],
    ['schedule.cancel', 'Cancelar agendamento de notícia', 2, S],
    ['audit.view', 'Auditoria de notícias', 3, O],
    ['settings.manage', 'Configurar o módulo de notícias', 3, O],
  ]),
  calendario: grantSet('calendario', [
    ['create', 'Criar eventos', 1, S],
    ['update', 'Editar eventos', 2, S],
    ['delete', 'Excluir eventos', 2, S],
    ['import_ics', 'Importar calendário ICS', 2, S],
    ['export_ics', 'Exportar/assinar calendário ICS', 0, A],
    ['holidays.manage', 'Gerenciar feriados', 2, S],
    ['notify', 'Notificar convidados do calendário', 2, S],
    ['company.view', 'Ver calendário corporativo', 0, A],
    ['company.config', 'Configurar ICS compartilhado', 3, O],
    ['sync', 'Sincronizar calendário externo', 2, S],
  ]),
  'ia-assistant': grantSet('ia-assistant', [
    ['voice', 'Usar voz no assistente', 0, A],
    ['config.manage', 'Configurar o assistente IA', 3, O],
    ['knowledge.view', 'Consultar base de conhecimento da IA', 0, A],
    ['knowledge.manage', 'Gerenciar base de conhecimento da IA', 3, O],
    ['feature_toggles.manage', 'Gerenciar feature toggles da IA', 3, O],
    ['sessions.cleanup', 'Limpar sessões globais da IA', 3, O],
    ['autonomous.control_any', 'Controlar agente autônomo de qualquer usuário', 3, O],
    ['tools.mutate', 'Executar ações de escrita via IA (aprovar, reprovar)', 2, S],
    ['graph.email', 'IA ler e-mail (Graph)', 2, S],
    ['graph.teams', 'IA ler Teams (Graph)', 2, S],
    ['kpi_boards.create', 'IA criar quadros de KPI', 2, S],
    ['kpi_boards.delete', 'IA excluir quadros de KPI', 2, S],
    ['memory.manage', 'Gerenciar memória da IA', 3, O],
    ['skills.manage', 'Gerenciar skills da IA', 3, O],
  ]),
  ponto: grantSet('ponto', [
    ['punch', 'Registrar ponto', 0, A],
    ['view_own', 'Ver o próprio espelho de ponto', 0, A],
    ['view_all', 'Ver ponto de todos', 2, S],
    ['adjust', 'Ajustar/justificar marcações', 2, S],
    ['approve', 'Aprovar ajustes de ponto', 2, S],
    ['export', 'Exportar espelho de ponto', 2, S],
    ['settings.manage', 'Configurar PontoFlow', 3, O],
    ['biometric.manage', 'Gerenciar biometria WebAuthn', 0, A],
    ['close', 'Fechar período de ponto', 2, S],
    ['audit.view', 'Auditoria de ponto', 3, O],
  ]),
  contracheque: grantSet('contracheque', [
    ['view_own', 'Ver o próprio contracheque', 0, A],
    ['accept', 'Aceitar contracheque (ciência)', 0, A],
    ['download', 'Baixar o próprio contracheque', 0, A],
    ['view_all', 'Ver contracheque de todos', 3, O],
    ['publish', 'Publicar contracheques', 3, O],
    ['import', 'Importar contracheques', 3, O],
    ['export', 'Exportar contracheques', 3, O],
    ['notify', 'Notificar disponibilidade de contracheque', 3, O],
  ]),
  reembolso: grantSet('reimbursement', [
    ['view_own', 'Ver os próprios reembolsos', 0, A],
    ['view_all', 'Ver reembolsos de todos', 2, S],
    ['reject', 'Rejeitar reembolsos', 2, S],
    ['mark_paid', 'Marcar reembolso como pago', 2, S],
    ['delete', 'Excluir reembolsos', 3, O],
    ['pdf_own', 'Baixar PDF do próprio reembolso', 0, A],
    ['pdf_all', 'Baixar PDF de qualquer reembolso', 2, S],
    ['attach', 'Anexar comprovantes', 0, A],
    ['attachments.view_all', 'Ver anexos de qualquer reembolso', 2, S],
    ['export', 'Exportar reembolsos', 2, S],
    ['settings', 'Configurar e-mails e regras de reembolso', 3, O],
    ['finance.view', 'Fila do financeiro (pós-aprovação)', 2, S],
    ['notify', 'Reenviar notificações de reembolso', 2, S],
    ['reopen', 'Reabrir reembolso', 2, S],
    ['bulk_approve', 'Aprovar reembolsos em lote', 2, S],
    ['audit.view', 'Auditoria de reembolsos', 3, O],
  ]),
  kpi: grantSet('kpi', [
    ['bi.view', 'Ver dashboards BI e métricas', 0, S],
    ['bi.create', 'Criar dashboards BI', 1, S],
    ['bi.edit_any', 'Editar/excluir dashboards BI de outros', 3, O],
    ['cards.create', 'Criar cards de KPI', 1, S],
    ['cards.edit', 'Editar cards de KPI', 2, S],
    ['cards.delete', 'Excluir cards de KPI', 2, S],
    ['export', 'Exportar KPIs', 2, S],
    ['import', 'Importar dados de KPI', 2, S],
    ['ia_boards.view', 'Ver quadros de KPI da IA', 0, S],
    ['ia_boards.manage', 'Gerenciar quadros de KPI da IA', 2, S],
    ['share', 'Compartilhar KPIs', 2, S],
    ['datasources.manage', 'Gerenciar fontes de dados de KPI', 3, O],
    ['refresh', 'Forçar atualização de KPIs', 2, S],
    ['config', 'Configurar KPIs', 3, O],
  ]),
  avaliacao: grantSet('avaliacao', [
    ['create', 'Criar avaliações', 1, S],
    ['update', 'Editar avaliações', 2, S],
    ['delete', 'Mover avaliações para a lixeira / excluir', 2, S],
    ['restore', 'Restaurar avaliações da lixeira', 2, S],
    ['hard_delete', 'Excluir avaliação permanentemente', 3, O],
    ['approve_any', 'Aprovar avaliação de qualquer gerente', 3, O],
    ['finalize_any', 'Finalizar avaliação de qualquer gerente', 3, O],
    ['decide', 'Tomar decisão sobre avaliações', 2, S],
    ['criteria.view', 'Ver critérios de avaliação', 0, S],
    ['criteria.manage', 'Gerenciar critérios de avaliação', 3, O],
    ['metrics.view', 'Ver métricas de avaliação', 0, S],
    ['reports.view', 'Ver relatórios de avaliação', 3, O],
    ['reports.export', 'Exportar relatórios de avaliação', 3, O],
    ['settings.manage', 'Configurar avaliação de desempenho', 3, O],
    ['trash.view', 'Ver lixeira de avaliações', 2, S],
    ['trash.cleanup', 'Limpar lixeira de avaliações', 3, O],
    ['periods.manage', 'Gerenciar períodos de avaliação', 2, S],
    ['periods.notify', 'Notificar abertura de período', 2, S],
    ['eligible.manage', 'Gerenciar usuários elegíveis', 2, S],
    ['managers_map.manage', 'Gerenciar mapeamento colaborador-gerente', 2, S],
    ['cron.run', 'Executar criação automática de avaliações', 3, O],
    ['view_all', 'Ver avaliações de todos', 2, S],
    ['view_team', 'Ver avaliações da equipe', 1, S],
    ['final_comment', 'Registrar comentário final', 2, S],
    ['export_pdf', 'Exportar avaliação em PDF', 2, S],
    ['analytics.view', 'Análises avançadas de avaliação', 2, S],
    ['self.evaluate', 'Preencher autoavaliação', 0, N],
  ]),
  epi: grantSet('epi', [
    ['request', 'Solicitar EPI', 0, N],
    ['deliver', 'Registrar entrega de EPI', 2, S],
    ['sign', 'Assinar recebimento de EPI', 0, N],
    ['view_all', 'Ver registros de EPI de todos', 2, S],
    ['stock.view', 'Ver estoque de EPI', 2, S],
    ['stock.edit', 'Editar estoque de EPI', 2, S],
    ['stock.import', 'Importar estoque de EPI', 2, S],
    ['stock.export', 'Exportar estoque de EPI', 2, S],
    ['kits.manage', 'Gerenciar kits de EPI', 2, S],
    ['types.manage', 'Gerenciar tipos de EPI', 2, S],
    ['sector_responsibles.manage', 'Gerenciar responsáveis por setor', 3, S],
    ['report', 'Relatório de EPI', 2, S],
    ['reset', 'Zerar cadastro de EPI', 3, O],
    ['ca_lookup', 'Consultar CA de EPI', 2, S],
    ['delete', 'Excluir registros de EPI', 2, S],
  ]),
  ferias: grantSet('ferias', [
    ['view_own', 'Ver as próprias férias', 0, A],
    ['view_all', 'Ver férias de todos', 2, S],
    ['view_team', 'Ver férias da equipe', 1, S],
    ['reject', 'Reprovar pedidos de férias', 2, S],
    ['cancel_any', 'Cancelar férias de terceiros', 2, S],
    ['pdf_own', 'Baixar PDF das próprias férias', 0, A],
    ['pdf_all', 'Baixar PDF de férias de terceiros', 2, S],
    ['export', 'Exportar férias (XLSX/CSV)', 2, S],
    ['balance.edit', 'Editar saldo de férias', 3, O],
    ['periods.manage', 'Gerenciar períodos aquisitivos', 3, O],
    ['notify', 'Notificar sobre férias', 2, S],
    ['audit.view', 'Auditoria de férias', 3, O],
    ['signature.manage', 'Gerenciar assinaturas das férias', 2, S],
  ]),
  'lista-presenca': grantSet('lista-presenca', [
    ['update', 'Editar listas de presença', 2, S],
    ['delete', 'Excluir listas de presença', 2, S],
    ['manage_any', 'Gerenciar listas criadas por outros', 3, O],
    ['close', 'Encerrar listas de presença', 2, S],
    ['reopen', 'Reabrir listas de presença', 2, S],
    ['sign', 'Assinar lista de presença', 0, A],
    ['export', 'Exportar listas de presença', 2, S],
    ['pdf', 'Gerar PDF da lista de presença', 0, A],
    ['training.launch', 'Lançar treinamento em lote', 2, S],
    ['public_link.manage', 'Gerenciar link público da lista', 2, S],
    ['view_all', 'Ver listas de todos', 2, S],
    ['audit.view', 'Auditoria de listas', 3, O],
  ]),
  academy: grantSet('academy', [
    ['update_any', 'Editar qualquer curso', 3, O],
    ['delete_any', 'Excluir qualquer curso', 3, O],
    ['lessons.manage', 'Gerenciar aulas', 2, S],
    ['questions.manage', 'Gerenciar questões de prova', 3, O],
    ['certificates.download_own', 'Baixar o próprio certificado', 0, A],
    ['certificates.download_any', 'Baixar certificado de terceiros', 3, O],
    ['certificates.templates.manage', 'Gerenciar modelos de certificado', 3, O],
    ['certificates.issue', 'Emitir certificados', 2, S],
    ['progress.view_all', 'Ver progresso de todos os alunos', 3, O],
    ['categories.manage', 'Gerenciar categorias', 2, S],
    ['reports.view', 'Relatórios da Academy', 2, S],
    ['export', 'Exportar dados da Academy', 2, S],
    ['enrollments.manage', 'Gerenciar matrículas', 2, S],
    ['setup', 'Configurar/semear a Academy', 3, O],
  ]),
  biblioteca: grantSet('biblioteca', [
    ['download', 'Baixar arquivos da biblioteca', 0, A],
    ['upload', 'Enviar arquivos para a biblioteca', 1, S],
    ['create', 'Criar itens na biblioteca', 1, O],
    ['update', 'Editar itens da biblioteca', 2, O],
    ['delete', 'Excluir itens da biblioteca', 3, O],
    ['folders.manage', 'Gerenciar pastas', 3, O],
    ['share', 'Compartilhar itens', 2, S],
    ['permissions.manage', 'Gerenciar permissões de arquivos', 3, O],
  ]),
  ajuda: grantSet('ajuda', [
    ['view', 'Acessar central de ajuda', 0, N],
    ['manage', 'Gerenciar conteúdo de ajuda', 2, S],
    ['tickets.view_all', 'Ver chamados de todos', 2, S],
    ['tickets.reply', 'Responder chamados', 2, S],
  ]),
  manual: grantSet('manual', [
    ['view', 'Ver manual do colaborador', 0, N],
    ['manage', 'Editar manual do colaborador', 2, S],
    ['publish', 'Publicar manual', 2, S],
  ]),
  procedimentos: grantSet('procedimentos', [
    ['view', 'Ver procedimentos (POPs)', 0, N],
    ['manage', 'Editar procedimentos', 2, S],
    ['publish', 'Publicar procedimentos', 2, S],
    ['upload', 'Anexar documentos a procedimentos', 1, S],
  ]),
  politicas: grantSet('politicas', [
    ['view', 'Ver políticas', 0, N],
    ['manage', 'Editar políticas', 2, S],
    ['publish', 'Publicar políticas', 2, S],
    ['upload', 'Anexar documentos a políticas', 1, S],
  ]),
  compras: grantSet('compras', [
    ['create', 'Criar ordens de compra', 1, S],
    ['requests.create', 'Criar requisições de compra', 1, S],
    ['approve_any', 'Aprovar requisição de qualquer aprovador', 3, O],
    ['generate_po', 'Gerar ordem de compra a partir da requisição', 3, O],
    ['delete', 'Excluir ordens de compra', 3, O],
    ['config', 'Configurar compras (setores e aprovadores)', 3, O],
    ['pdf', 'Gerar PDF de compras', 2, S],
    ['send', 'Enviar ordem de compra ao fornecedor', 2, S],
    ['view_all', 'Ver ordens de todos', 3, O],
    ['suppliers.manage', 'Gerenciar fornecedores', 2, S],
    ['attachments.upload', 'Anexar documentos de compra', 1, S],
    ['export', 'Exportar compras', 2, S],
  ]),
  poliweb: grantSet('poliweb', [
    ['asos.view', 'Ver ASOs do PoliWeb', 2, S],
    ['asos.schedule', 'Agendar ASO', 2, S],
    ['sync', 'Sincronizar PoliWeb', 3, O],
    ['login.manage', 'Gerenciar credenciais do PoliWeb', 3, O],
    ['proxy', 'Usar proxy PoliWeb', 2, S],
    ['reports', 'Relatórios do PoliWeb', 2, S],
    ['export', 'Exportar dados do PoliWeb', 2, S],
  ]),
  'man-schedule': grantSet('man-schedule', [
    ['realtime.view', 'Ver escala em tempo real', 0, S],
    ['edit', 'Editar escala', 2, S],
    ['export', 'Exportar escala', 2, S],
    ['print', 'Imprimir escala', 0, S],
    ['history.view', 'Ver histórico da escala', 0, S],
    ['config', 'Configurar Man Schedule', 3, O],
    ['sync', 'Sincronizar escala', 3, O],
  ]),
  chat: grantSet('chat', [
    ['moderate', 'Moderar chat (qualquer canal/servidor)', 3, O],
    ['channels.create', 'Criar canais', 3, O],
    ['servers.create', 'Criar servidores de chat', 2, S],
    ['servers.delete_any', 'Excluir qualquer servidor', 3, O],
    ['messages.delete_any', 'Excluir mensagens de terceiros', 3, O],
    ['messages.edit_own', 'Editar as próprias mensagens', 0, A],
    ['attach', 'Anexar arquivos no chat', 0, A],
    ['dm', 'Mensagens diretas', 0, A],
    ['presence.view', 'Ver presença online', 0, A],
    ['history.export', 'Exportar histórico de chat', 3, O],
    ['mention_all', 'Mencionar todos', 2, S],
  ]),
  wkradar: grantSet('wkradar', [
    ['credentials.view_all', 'Listar todas as credenciais WK Radar', 3, O],
    ['credentials.manage', 'Criar/remover credenciais WK Radar', 3, O],
    ['card.seed', 'Criar card WK Radar', 3, O],
    ['launch', 'Abrir WK Radar', 2, S],
    ['audit.view', 'Auditoria do WK Radar', 3, O],
  ]),
  contatos: grantSet('contatos', [
    ['view', 'Ver lista de ramais', 0, N],
    ['manage', 'Gerenciar ramais', 2, S],
    ['export', 'Exportar ramais', 2, S],
  ]),
  emergencia: grantSet('emergencia', [
    ['view', 'Ver procedimentos de emergência', 0, N],
    ['manage', 'Gerenciar procedimentos de emergência', 2, S],
  ]),
  guia_offshore: grantSet('guia_offshore', [
    ['view', 'Ver guia offshore', 0, N],
    ['manage', 'Gerenciar guia offshore', 2, S],
  ]),
  notifications: grantSet('notifications', [
    ['view_all', 'Ver todas as notificações enviadas', 2, S],
    ['history.view', 'Histórico de notificações', 2, S],
    ['purge', 'Limpar notificações antigas', 3, O],
    ['push.manage', 'Gerenciar Web Push (VAPID)', 3, O],
    ['templates.manage', 'Gerenciar modelos de notificação', 3, O],
    ['prefs.manage_all', 'Gerenciar preferências de todos', 3, O],
    ['delete', 'Excluir notificações', 2, S],
    ['targets.sector', 'Enviar para setor', 2, S],
    ['targets.role', 'Enviar para papel', 2, S],
    ['email.send', 'Enviar e-mail de notificação', 2, S],
    ['test', 'Testar notificações', 3, O],
  ]),
  feedback: grantSet('feedback', [
    ['view', 'Ver feedbacks dos usuários', 3, O],
    ['respond', 'Responder feedbacks', 3, O],
    ['export', 'Exportar feedbacks', 3, O],
    ['delete', 'Excluir feedbacks', 3, O],
  ]),
  metrics: grantSet('metrics', [
    ['view', 'Ver métricas gerais', 3, O],
    ['export', 'Exportar métricas', 3, O],
    ['wau.view', 'Ver usuários ativos semanais', 3, O],
    ['support.view', 'Ver métricas de suporte', 3, O],
  ]),
  engagement: grantSet('engagement', [
    ['view', 'Ver engajamento de notícias', 3, O],
    ['export', 'Exportar engajamento', 3, O],
  ]),
  admin: grantSet('admin', [
    ['users.view', 'Listar usuários', 3, O],
    ['users.create', 'Criar usuários', 3, O],
    ['users.edit', 'Editar usuários', 3, O],
    ['users.delete', 'Excluir usuários', 3, O],
    ['users.role', 'Alterar papel (role) de usuários', 3, O],
    ['users.reset_password', 'Redefinir senha de usuários', 3, O],
    ['users.permissions.view', 'Ver permissões dos usuários', 3, O],
    ['users.permissions.update', 'Alterar permissões dos usuários', 3, O],
    ['users.access_history.view', 'Ver histórico de acesso dos usuários', 2, O],
    ['users.access_history.record', 'Registrar eventos no histórico de acesso', 3, O],
    ['users.access_history.clear', 'Limpar histórico de acesso', 3, O],
    ['users.ban', 'Banir/desbanir usuários', 3, O],
    ['users.import', 'Importar usuários', 3, O],
    ['users.export', 'Exportar usuários', 3, O],
    ['users.startup_experience', 'Configurar splash e som de abertura', 3, O],
    ['sectors.manage', 'Gerenciar setores', 3, O],
    ['cards.manage', 'Gerenciar cards', 3, O],
    ['modules.manage', 'Gerenciar módulos', 3, O],
    ['menu.manage', 'Gerenciar menu e traduções', 3, O],
    ['email_settings.manage', 'Configurar e-mail do portal', 3, O],
    ['secrets.manage', 'Gerenciar segredos (app_secrets)', 3, O],
    ['api_keys.manage', 'Gerenciar chaves de API', 3, O],
    ['logs.view', 'Ver logs do sistema', 3, O],
    ['audit.view', 'Ver auditoria do sistema', 3, O],
    ['sql.execute', 'Executar SQL administrativo', 3, O],
    ['reimbursement_settings.manage', 'Configurar reembolso (admin)', 3, O],
    ['cron.run', 'Executar crons manualmente', 3, O],
    ['notifications.manage', 'Gerenciar notificações (admin)', 3, O],
    ['academy.manage', 'Administrar Academy', 3, O],
  ]),
  'integracao-erp': grantSet('integracao-erp', [
    ['sync', 'Sincronizar com o MIO', 3, O],
    ['cache.refresh', 'Atualizar cache MIO', 3, O],
    ['config', 'Configurar integração ERP', 3, O],
    ['logs.view', 'Ver logs da integração', 3, O],
  ]),
  'gestao-tripulantes': grantSet('gestao-tripulantes', [
    ['colaboradores.view', 'Ver fichas de colaboradores', 0, S],
    ['colaboradores.export', 'Exportar colaboradores', 2, S],
    ['export', 'Exportar relatórios do módulo', 2, S],
    ['escala.view', 'Ver escala', 0, S],
    ['escala.edit', 'Editar escala', 2, S],
    ['embarques.create', 'Lançar embarques', 2, S],
    ['embarques.edit', 'Editar embarques', 2, S],
    ['embarques.delete', 'Excluir embarques', 2, S],
    ['afastamentos.manage', 'Gerenciar afastamentos', 2, S],
    ['fechamento.view', 'Ver fechamento mensal', 0, S],
    ['fechamento.approve', 'Assinar/aprovar fechamento', 2, S],
    ['fechamento.export', 'Exportar fechamento (XLSX)', 2, S],
    ['aso.view', 'Ver ASO', 0, S],
    ['aso.schedule', 'Agendar ASO (DP)', 2, S],
    ['aso.approve', 'Aprovar/reprovar agendamento de ASO (logística)', 2, S],
    ['treinamentos.view', 'Ver treinamentos', 0, S],
    ['treinamentos.edit', 'Lançar/editar treinamentos', 2, S],
    ['desligamento.manage', 'Gerenciar desligamento (rescisão)', 2, S],
    ['mio.sync', 'Sincronizar MIO (cópia canônica)', 3, O],
    ['poliweb.view', 'Ver dados PoliWeb', 0, S],
    ['ocr.review', 'Revisar OCR de documentos', 2, S],
    ['documents.view', 'Ver documentos do cadastro', 0, S],
    ['documents.download', 'Baixar documentos do cadastro', 0, S],
    // Setor DP/RH + GT também vê todos (código, `documento-escopo.ts`); `false` no JSONB do usuário nega.
    ['documents.view_all', 'Ver documentos pessoais de todos os colaboradores', 2, S],
    // Implícito no código para quem tem vínculo `gt_colaboradores.user_id`; role ACL de USER abriria o módulo.
    ['documents.view_own', 'Ver os próprios documentos pessoais', 0, N],
    ['passaportes.manage', 'Gerenciar passaportes', 2, S],
    ['matrizes.import', 'Importar matriz de treinamento (XLSX MIO)', 2, S],
    ['configuracoes.manage', 'Configurar o módulo', 3, S],
    ['lookups.manage', 'Gerenciar cargos, departamentos e empresas', 2, S],
    ['audit.view', 'Auditoria de edições da escala', 2, S],
  ]),
  'e-social': grantSet('e-social', [
    ['events.create', 'Criar eventos e-Social', 1, S],
    ['events.edit', 'Editar eventos e-Social', 2, S],
    ['events.delete', 'Excluir eventos e-Social', 3, O],
    ['matricula.edit', 'Corrigir matrícula do evento', 2, S],
    ['xml.download', 'Baixar XML dos eventos', 0, S],
    ['certificado.manage', 'Gerenciar certificado digital', 3, O],
    ['configuracoes.manage', 'Configurar e-Social', 3, O],
    ['consolidar', 'Consolidar eventos', 2, S],
    ['resend', 'Reenviar eventos rejeitados', 3, O],
    ['receipt.query', 'Consultar recibo/protocolo', 0, S],
    ['export', 'Exportar eventos', 2, S],
  ]),
  indicadores: grantSet('indicadores', [
    ['export', 'Exportar planilhas de indicadores', 2, S],
    ['rows.delete', 'Excluir linhas das planilhas', 2, S],
    ['sheets.delete', 'Excluir planilhas', 3, O],
    ['columns.manage', 'Gerenciar colunas das abas', 2, S],
    ['history.view', 'Histórico de importações', 0, S],
  ]),
  dp: grantSet('dp', [
    ['colaboradores.view', 'Ver colaboradores', 0, S],
    ['colaboradores.create', 'Cadastrar colaboradores', 1, S],
    ['colaboradores.edit', 'Editar colaboradores', 2, S],
    ['colaboradores.delete', 'Excluir colaboradores', 3, O],
    ['folha.view', 'Ver folha no DP', 0, S],
    ['ferias.view', 'Ver férias no DP', 0, S],
    ['aso.view', 'Ver vencimentos de ASO', 0, S],
    ['aso.schedule', 'Agendar ASO', 2, S],
    ['export', 'Exportar listas do DP', 2, S],
    ['contracheque.publish', 'Publicar contracheque', 3, O],
    ['desligamento.manage', 'Gerenciar desligamentos', 2, S],
    ['escala.view', 'Ver escala no DP', 0, S],
  ]),
  recrutamento: grantSet('recrutamento', [
    ['vagas.view', 'Ver vagas', 0, S],
    ['vagas.sync', 'Sincronizar vagas do InHire', 2, S],
    ['candidatos.view', 'Ver candidatos', 0, S],
    ['candidatos.advance', 'Avançar candidato no funil', 2, S],
    ['candidatos.reject', 'Reprovar candidato', 2, S],
    ['precadastro.send', 'Enviar pré-cadastro ao DP', 2, S],
    ['inhire.configure', 'Configurar credenciais InHire', 3, O],
    ['export', 'Exportar recrutamento', 2, S],
  ]),
  financeiro: grantSet('financeiro', [
    ['faturas.create', 'Emitir faturas', 2, S],
    ['faturas.cancel', 'Cancelar faturas', 3, O],
    ['nfse.emit', 'Emitir NFS-e', 2, S],
    ['nfse.cancel', 'Cancelar NFS-e', 3, O],
    ['bancos.manage', 'Gerenciar bancos', 3, O],
    ['cobrancas.generate', 'Gerar cobranças', 2, S],
    ['conciliacao.run', 'Conciliar extratos', 2, S],
    ['certificado.manage', 'Gerenciar certificado A1', 3, O],
    ['clientes.manage', 'Gerenciar clientes', 2, S],
    ['templates.manage', 'Gerenciar templates', 3, O],
    ['export', 'Exportar financeiro', 2, S],
    ['folha.export', 'Exportar folha', 2, S],
    ['folha.close', 'Fechar competência da folha', 2, S],
    ['folha.import', 'Importar lançamentos da folha', 2, S],
    ['rubricas.manage', 'Gerenciar rubricas', 2, S],
    ['timesheet.import', 'Importar horas do ponto na folha', 2, S],
    ['contracheque.publish', 'Publicar contracheques da folha', 3, O],
    ['audit.view', 'Auditoria financeira', 3, O],
  ]),
};

/** Recursos ACL sem módulo na sidebar (`EXTRA_ACL_RESOURCES`). */
export const EXTRA_RESOURCE_GRANTS: Record<string, GrantSet> = {
  comments: grantSet('comments', [
    ['pin', 'Fixar comentários', 2, S],
    ['report', 'Denunciar comentários', 0, A],
  ]),
  reminders: grantSet('reminders', [
    ['read', 'Ver lembretes', 0, A],
    ['update', 'Editar lembretes', 1, A],
    ['delete', 'Excluir lembretes', 1, A],
    ['process', 'Processar lembretes (cron)', 3, O],
  ]),
  social: grantSet('social', [
    ['delete.any', 'Excluir posts de terceiros', 2, O],
    ['story.moderate', 'Moderar stories', 2, S],
    ['report', 'Denunciar posts', 0, A],
    ['pin', 'Fixar posts', 2, S],
    ['export', 'Exportar dados sociais', 2, S],
    ['settings', 'Configurar rede social', 3, O],
    ['mention', 'Mencionar usuários', 0, A],
  ]),
};
